---
name: Apex Fusion Reactor - Bridging transactions
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  security-events: write

jobs:
  bridging:
    name: Bridging transactions
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
      - name: Setup Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          check-latest: true
          cache: 'pip'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Start bridging
        run: python main.py
        env:
          PYTHONUNBUFFERED: 1
          SIGN_KEY: ${{ secrets.SIGN_KEY }}
          PRIME_WALLET_RECOVERY_PHRASE: ${{ secrets.PRIME_WALLET_RECOVERY_PHRASE }}
          VECTOR_WALLET_RECOVERY_PHRASE: ${{ secrets.VECTOR_WALLET_RECOVERY_PHRASE }}
          NEXUS_WALLET_RECOVERY_PHRASE: ${{ secrets.NEXUS_WALLET_RECOVERY_PHRASE }}
          NEXUS_NETWORK_NAME: ${{ vars.NEXUS_NETWORK_NAME }}
          NEXUS_NETWORK_RPC_URL: ${{ vars.NEXUS_NETWORK_RPC_URL }}
          NEXUS_NETWORK_CHAIN_ID: ${{ vars.NEXUS_NETWORK_CHAIN_ID }}
          NEXUS_NETWORK_CURRENCY_SYMBOL: ${{ vars.NEXUS_NETWORK_CURRENCY_SYMBOL }}
          PRIME_TO_VECTOR_AMOUNT: ${{ vars.PRIME_TO_VECTOR_AMOUNT }}
          PRIME_TO_NEXUS_AMOUNT: ${{ vars.PRIME_TO_NEXUS_AMOUNT }}
          VECTOR_TO_PRIME_AMOUNT: ${{ vars.VECTOR_TO_PRIME_AMOUNT }}
          NEXUS_TO_PRIME_AMOUNT: ${{ vars.NEXUS_TO_PRIME_AMOUNT }}
          APEX_FUSION_REACTOR_URL: ${{ vars.APEX_FUSION_REACTOR_URL }}
          APEX_FUSION_FAUCET_URL: ${{ vars.APEX_FUSION_FAUCET_URL }}
