---
name: Bridging transactions
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  security-events: write

jobs:
  bridging:
    name: Apex Fusion React - Bridging transactions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
      - name: Setup Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          check-latest: true
          cache: 'pip'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install Chrome
        run: |
          sudo apt update
          sudo wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -O /opt/google-chrome.deb
          sudo apt install /opt/google-chrome.deb
          sudo apt --fix-broken install
      - name: Start bridging
        run: python main.py
        env:
          SIGN_KEY=${{ secrets.SIGN_KEY }}
          PRIME_WALLET_RECOVERY_PHRASE=${{ secrets.PRIME_WALLET_RECOVERY_PHRASE }}
          VECTOR_WALLET_RECOVERY_PHRASE=${{ secrets.VECTOR_WALLET_RECOVERY_PHRASE }}
          NEXUS_WALLET_RECOVERY_PHRASE=${{ secrets.NEXUS_WALLET_RECOVERY_PHRASE }}
          NEXUS_NETWORK_NAME=${{ secrets.NEXUS_NETWORK_NAME }}
          NEXUS_NETWORK_RPC_URL=${{ secrets.NEXUS_NETWORK_RPC_URL }}
          NEXUS_NETWORK_CHAIN_ID=${{ secrets.NEXUS_NETWORK_CHAIN_ID }}
          NEXUS_NETWORK_CURRENCY_SYMBOL=${{ secrets.NEXUS_NETWORK_CURRENCY_SYMBOL }}
          PRIME_TO_VECTOR_AMOUNT=${{ secrets.PRIME_TO_VECTOR_AMOUNT }}
          PRIME_TO_NEXUS_AMOUNT=${{ secrets.PRIME_TO_NEXUS_AMOUNT }}
          VECTOR_TO_PRIME_AMOUNT=${{ secrets.VECTOR_TO_PRIME_AMOUNT }}
          NEXUS_TO_PRIME_AMOUNT=${{ secrets.NEXUS_TO_PRIME_AMOUNT }}
          APEX_FUSION_REACTOR_URL=${{ secrets.APEX_FUSION_REACTOR_URL }}
          APEX_FUSION_FAUCET_URL=${{ secrets.APEX_FUSION_FAUCET_URL }}
