---
name: Multiple Skyline Transactions

on:
  schedule:
    - cron: "0 6,13 * * *"

  workflow_dispatch:
    inputs:
      notification:
        type: boolean
        required: false
        description: "Notification"
        default: true

permissions:
  id-token: write
  contents: read
  security-events: write

jobs:
  source_prime:
    name: Source Prime
    uses: ./.github/workflows/source-prime.yml
    with:
      bridge_name: Skyline
      notification: false
    secrets: inherit

  source_preview:
    name: Source Preview
    uses: ./.github/workflows/source-preview.yml
    with:
      bridge_name: Skyline
      notification: false
    secrets: inherit

  source_vector:
    name: Source Vector
    uses: ./.github/workflows/source-vector.yml
    with:
      bridge_name: Skyline
      notification: false
    secrets: inherit

  source_nexus:
    name: Source Nexus
    uses: ./.github/workflows/source-nexus.yml
    with:
      bridge_name: Skyline
      notification: false
    secrets: inherit

  source_polygon:
    name: Source Polygon
    uses: ./.github/workflows/source-polygon.yml
    with:
      bridge_name: Skyline
      notification: false
    secrets: inherit

  source_ethereum:
    name: Source Ethereum
    uses: ./.github/workflows/source-ethereum.yml
    with:
      bridge_name: Skyline
      notification: false
    secrets: inherit

  source_katana:
    name: Source Katana
    uses: ./.github/workflows/source-katana.yml
    with:
      bridge_name: Skyline
      notification: false
    secrets: inherit

  source_sei:
    name: Source Sei
    uses: ./.github/workflows/source-sei.yml
    with:
      bridge_name: Skyline
      notification: false
    secrets: inherit

  source_scroll:
    name: Source Scroll
    uses: ./.github/workflows/source-scroll.yml
    with:
      bridge_name: Skyline
      notification: false
    secrets: inherit

  source_unichain:
    name: Source Unichain
    uses: ./.github/workflows/source-unichain.yml
    with:
      bridge_name: Skyline
      notification: false
    secrets: inherit
