---
name: Multiple Reactor Partner Transactions
on:
  schedule:
    - cron: '30 4,11 * * *'
  workflow_dispatch:
    inputs:
      notification:
        required: false
        description: Notification
        type: boolean
        default: true

permissions:
  id-token: write
  contents: read
  security-events: write

jobs:
  prime_to_nexus:
    name: Prime to Nexus
    uses: ./.github/workflows/single-transaction.yml
    with:
      bridge: Reactor
      url: ${{ vars.REACTOR_URL }}
      source_chain: Prime
      amount: 5
      source_token: AP3X
      destination_chain: Nexus
      destination_token: AP3X
      notification: false
    secrets:
      SIGN_KEY: ${{ secrets.SIGN_KEY }}
      CHROME_URL: ${{ secrets.CHROME_URL }}
      CHROME_CONFIGS_URL: ${{ secrets.CHROME_CONFIGS_URL }}
  nexus_to_prime:
    name: Nexus to Prime
    uses: ./.github/workflows/single-transaction.yml
    with:
      bridge: Reactor
      url: ${{ vars.REACTOR_URL }}
      source_chain: Nexus
      amount: 2
      source_token: AP3X
      destination_chain: Prime
      destination_token: AP3X
      notification: false
    secrets:
      SIGN_KEY: ${{ secrets.SIGN_KEY }}
      CHROME_URL: ${{ secrets.CHROME_URL }}
      CHROME_CONFIGS_URL: ${{ secrets.CHROME_CONFIGS_URL }}
  inputs_check:
    name: Inputs Check
    runs-on: ubuntu-latest
    outputs:
      notification: ${{ steps.notification_input_check.outputs.notification }}
    steps:
      - name: Notification Input Check
        id: notification_input_check
        run: |
          if [[ "${{ inputs.notification }}" != "false" ]]; then
            echo "notification=true" >> $GITHUB_OUTPUT
          else
            echo "notification=false" >> $GITHUB_OUTPUT
          fi
  notification:
    name: Send notification
    uses: ./.github/workflows/multiple-transactions-notification.yml
    needs: [prime_to_nexus, nexus_to_prime, inputs_check]
    if: (!cancelled() && (needs.inputs_check.outputs.notification == 'true'))
    with:
      bridge: Reactor
      tx_01_source_chain: Prime
      tx_01_source_token: AP3X
      tx_01_destination_chain: Nexus
      tx_01_destination_token: AP3X
      tx_01_source_status: ${{ needs.prime_to_nexus.outputs.source_status }}
      tx_01_bridge_status: ${{ needs.prime_to_nexus.outputs.bridge_status }}
      tx_01_destination_status: ${{ needs.prime_to_nexus.outputs.destination_status }}
      tx_01_status: ${{ needs.prime_to_nexus.outputs.bridging_status }}
      tx_02_source_chain: Nexus
      tx_02_source_token: AP3X
      tx_02_destination_chain: Prime
      tx_02_destination_token: AP3X
      tx_02_source_status: ${{ needs.nexus_to_prime.outputs.source_status }}
      tx_02_bridge_status: ${{ needs.nexus_to_prime.outputs.bridge_status }}
      tx_02_destination_status: ${{ needs.nexus_to_prime.outputs.destination_status }}
      tx_02_status: ${{ needs.nexus_to_prime.outputs.bridging_status }}
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
