---
name: Multiple Skyline Partner Transactions
on:
  schedule:
    - cron: '0 6,13 * * *'
  workflow_dispatch:
    inputs:
      notification:
        required: false
        description: Notification
        type: boolean
        default: true

permissions:
  id-token: write
  contents: read
  security-events: write

jobs:
  prime_ap3x_to_preview_cap3x:
    name: Prime(AP3X) to Preview(cAP3X)
    uses: ./.github/workflows/single-transaction.yml
    with:
      bridge: Skyline
      url: ${{ vars.SKYLINE_URL }}
      source_chain: Prime
      amount: 5
      source_token: AP3X
      destination_chain: Preview
      destination_token: cAP3X
      notification: false
    secrets:
      SIGN_KEY: ${{ secrets.SIGN_KEY }}
      CHROME_URL: ${{ secrets.CHROME_URL }}
      CHROME_CONFIGS_URL: ${{ secrets.CHROME_CONFIGS_URL }}
  preview_cap3x_to_prime_ap3x:
    name: Preview(cAP3X) to Prime(AP3X)
    uses: ./.github/workflows/single-transaction.yml
    with:
      bridge: Skyline
      url: ${{ vars.SKYLINE_URL }}
      source_chain: Preview
      amount: 2
      source_token: cAP3X
      destination_chain: Prime
      destination_token: AP3X
      notification: false
    secrets:
      SIGN_KEY: ${{ secrets.SIGN_KEY }}
      CHROME_URL: ${{ secrets.CHROME_URL }}
      CHROME_CONFIGS_URL: ${{ secrets.CHROME_CONFIGS_URL }}
  inputs_check:
    name: Inputs Check
    runs-on: ubuntu-latest
    outputs:
      notification: ${{ steps.notification_input_check.outputs.notification }}
    steps:
      - name: Notification Input Check
        id: notification_input_check
        run: |
          if [[ "${{ inputs.notification }}" != "false" ]]; then
            echo "notification=true" >> $GITHUB_OUTPUT
          else
            echo "notification=false" >> $GITHUB_OUTPUT
          fi
  notification:
    name: Send notification
    uses: ./.github/workflows/multiple-transactions-notification.yml
    needs: [prime_ap3x_to_preview_cap3x, preview_cap3x_to_prime_ap3x, inputs_check]
    if: (!cancelled() && (needs.inputs_check.outputs.notification == 'true'))
    with:
      bridge: Skyline
      tx_01_source_chain: Prime
      tx_01_source_token: AP3X
      tx_01_destination_chain: Preview
      tx_01_destination_token: cAP3X
      tx_01_source_status: ${{ needs.prime_ap3x_to_preview_cap3x.outputs.source_status }}
      tx_01_bridge_status: ${{ needs.prime_ap3x_to_preview_cap3x.outputs.bridge_status }}
      tx_01_destination_status: ${{ needs.prime_ap3x_to_preview_cap3x.outputs.destination_status }}
      tx_01_status: ${{ needs.prime_ap3x_to_preview_cap3x.outputs.bridging_status }}
      tx_02_source_chain: Preview
      tx_02_source_token: cAP3X
      tx_02_destination_chain: Prime
      tx_02_destination_token: AP3X
      tx_02_source_status: ${{ needs.preview_cap3x_to_prime_ap3x.outputs.source_status }}
      tx_02_bridge_status: ${{ needs.preview_cap3x_to_prime_ap3x.outputs.bridge_status }}
      tx_02_destination_status: ${{ needs.preview_cap3x_to_prime_ap3x.outputs.destination_status }}
      tx_02_status: ${{ needs.preview_cap3x_to_prime_ap3x.outputs.bridging_status }}
      
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
