---
name: Multiple Skyline Partner Transactions
on:
  schedule:
    - cron: '0 6,13 * * *'
  workflow_dispatch:
    inputs:
      notification:
        required: false
        description: Notification
        type: boolean
        default: true

permissions:
  id-token: write
  contents: read
  security-events: write

jobs:
  prime_ap3x_to_preview_cap3x:
    name: Prime(AP3X) to Preview(cAP3X)
    uses: ./.github/workflows/single-transaction.yml
    with:
      bridge: Skyline
      url: ${{ vars.SKYLINE_URL }}
      source_chain: Prime
      amount: 5
      source_token: AP3X
      destination_chain: Preview
      destination_token: cAP3X
      notification: false
    secrets:
      SIGN_KEY: ${{ secrets.SIGN_KEY }}
      CHROME_URL: ${{ secrets.CHROME_URL }}
      CHROME_CONFIGS_URL: ${{ secrets.CHROME_CONFIGS_URL }}
  prime_ap3x_to_vector_ap3x:
    name: Prime(AP3X) to Vector(AP3X)
    uses: ./.github/workflows/single-transaction.yml
    needs: prime_ap3x_to_preview_cap3x
    with:
      bridge: Skyline
      url: ${{ vars.SKYLINE_URL }}
      source_chain: Prime
      amount: 6
      source_token: AP3X
      destination_chain: Vector
      destination_token: AP3X
      notification: false
    secrets:
      SIGN_KEY: ${{ secrets.SIGN_KEY }}
      CHROME_URL: ${{ secrets.CHROME_URL }}
      CHROME_CONFIGS_URL: ${{ secrets.CHROME_CONFIGS_URL }}
  prime_ap3x_to_nexus_ap3x:
    name: Prime(AP3X) to Nexus(AP3X)
    uses: ./.github/workflows/single-transaction.yml
    needs: prime_ap3x_to_vector_ap3x
    with:
      bridge: Skyline
      url: ${{ vars.SKYLINE_URL }}
      source_chain: Prime
      amount: 6
      source_token: AP3X
      destination_chain: Nexus
      destination_token: AP3X
      notification: false
    secrets:
      SIGN_KEY: ${{ secrets.SIGN_KEY }}
      CHROME_URL: ${{ secrets.CHROME_URL }}
      CHROME_CONFIGS_URL: ${{ secrets.CHROME_CONFIGS_URL }}
  preview_cap3x_to_prime_ap3x:
    name: Preview(cAP3X) to Prime(AP3X)
    uses: ./.github/workflows/single-transaction.yml
    with:
      bridge: Skyline
      url: ${{ vars.SKYLINE_URL }}
      source_chain: Preview
      amount: 2
      source_token: cAP3X
      destination_chain: Prime
      destination_token: AP3X
      notification: false
    secrets:
      SIGN_KEY: ${{ secrets.SIGN_KEY }}
      CHROME_URL: ${{ secrets.CHROME_URL }}
      CHROME_CONFIGS_URL: ${{ secrets.CHROME_CONFIGS_URL }}
  preview_ada_to_vector_xada:
    name: Preview(ADA) to Vector(xADA)
    uses: ./.github/workflows/single-transaction.yml
    needs: preview_cap3x_to_prime_ap3x
    with:
      bridge: Skyline
      url: ${{ vars.SKYLINE_URL }}
      source_chain: Preview
      amount: 2
      source_token: ADA
      destination_chain: Vector
      destination_token: xADA
      notification: false
    secrets:
      SIGN_KEY: ${{ secrets.SIGN_KEY }}
      CHROME_URL: ${{ secrets.CHROME_URL }}
      CHROME_CONFIGS_URL: ${{ secrets.CHROME_CONFIGS_URL }}
  preview_ada_to_nexus_xada:
    name: Preview(ADA) to Nexus(xADA)
    uses: ./.github/workflows/single-transaction.yml
    needs: preview_ada_to_vector_xada
    with:
      bridge: Skyline
      url: ${{ vars.SKYLINE_URL }}
      source_chain: Preview
      amount: 5
      source_token: ADA
      destination_chain: Nexus
      destination_token: xADA
      notification: false
    secrets:
      SIGN_KEY: ${{ secrets.SIGN_KEY }}
      CHROME_URL: ${{ secrets.CHROME_URL }}
      CHROME_CONFIGS_URL: ${{ secrets.CHROME_CONFIGS_URL }}
  vector_ap3x_to_prime_ap3x:
    name: Vector(AP3X) to Prime(AP3X)
    uses: ./.github/workflows/single-transaction.yml
    with:
      bridge: Skyline
      url: ${{ vars.SKYLINE_URL }}
      source_chain: Vector
      amount: 2
      source_token: AP3X
      destination_chain: Prime
      destination_token: AP3X
      notification: false
    secrets:
      SIGN_KEY: ${{ secrets.SIGN_KEY }}
      CHROME_URL: ${{ secrets.CHROME_URL }}
      CHROME_CONFIGS_URL: ${{ secrets.CHROME_CONFIGS_URL }}
  vector_xada_to_preview_ada:
    name: Vector(xADA) to Preview(ADA)
    uses: ./.github/workflows/single-transaction.yml
    needs: vector_ap3x_to_prime_ap3x
    with:
      bridge: Skyline
      url: ${{ vars.SKYLINE_URL }}
      source_chain: Vector
      amount: 5
      source_token: xADA
      destination_chain: Preview
      destination_token: ADA
      notification: false
    secrets:
      SIGN_KEY: ${{ secrets.SIGN_KEY }}
      CHROME_URL: ${{ secrets.CHROME_URL }}
      CHROME_CONFIGS_URL: ${{ secrets.CHROME_CONFIGS_URL }}
  vector_ap3x_to_nexus_ap3x:
    name: Vector(AP3X) to Nexus(AP3X)
    uses: ./.github/workflows/single-transaction.yml
    needs: vector_xada_to_preview_ada
    with:
      bridge: Skyline
      url: ${{ vars.SKYLINE_URL }}
      source_chain: Vector
      amount: 2
      source_token: AP3X
      destination_chain: Nexus
      destination_token: AP3X
      notification: false
    secrets:
      SIGN_KEY: ${{ secrets.SIGN_KEY }}
      CHROME_URL: ${{ secrets.CHROME_URL }}
      CHROME_CONFIGS_URL: ${{ secrets.CHROME_CONFIGS_URL }}
  vector_xada_to_nexus_xada:
    name: Vector(xADA) to Nexus(xADA)
    uses: ./.github/workflows/single-transaction.yml
    needs: vector_ap3x_to_nexus_ap3x
    with:
      bridge: Skyline
      url: ${{ vars.SKYLINE_URL }}
      source_chain: Vector
      amount: 5
      source_token: xADA
      destination_chain: Nexus
      destination_token: xADA
      notification: false
    secrets:
      SIGN_KEY: ${{ secrets.SIGN_KEY }}
      CHROME_URL: ${{ secrets.CHROME_URL }}
      CHROME_CONFIGS_URL: ${{ secrets.CHROME_CONFIGS_URL }}
  vector_mytesttoken_to_nexus_mytesttoken:
    name: Vector(myTestToken) to Nexus(myTestToken)
    uses: ./.github/workflows/single-transaction.yml
    needs: vector_xada_to_nexus_xada
    with:
      bridge: Skyline
      url: ${{ vars.SKYLINE_URL }}
      source_chain: Vector
      amount: 2
      source_token: myTestToken
      destination_chain: Nexus
      destination_token: myTestToken
      notification: false
    secrets:
      SIGN_KEY: ${{ secrets.SIGN_KEY }}
      CHROME_URL: ${{ secrets.CHROME_URL }}
      CHROME_CONFIGS_URL: ${{ secrets.CHROME_CONFIGS_URL }}
  nexus_ap3x_to_prime_ap3x:
    name: Nexus(AP3X) to Prime(AP3X)
    uses: ./.github/workflows/single-transaction.yml
    with:
      bridge: Skyline
      url: ${{ vars.SKYLINE_URL }}
      source_chain: Nexus
      amount: 2
      source_token: AP3X
      destination_chain: Prime
      destination_token: AP3X
      notification: false
    secrets:
      SIGN_KEY: ${{ secrets.SIGN_KEY }}
      CHROME_URL: ${{ secrets.CHROME_URL }}
      CHROME_CONFIGS_URL: ${{ secrets.CHROME_CONFIGS_URL }}
  nexus_ap3x_to_vector_ap3x:
    name: Nexus(AP3X) to Vector(AP3X)
    uses: ./.github/workflows/single-transaction.yml
    needs: nexus_ap3x_to_prime_ap3x
    with:
      bridge: Skyline
      url: ${{ vars.SKYLINE_URL }}
      source_chain: Nexus
      amount: 2
      source_token: AP3X
      destination_chain: Vector
      destination_token: AP3X
      notification: false
    secrets:
      SIGN_KEY: ${{ secrets.SIGN_KEY }}
      CHROME_URL: ${{ secrets.CHROME_URL }}
      CHROME_CONFIGS_URL: ${{ secrets.CHROME_CONFIGS_URL }}
  nexus_xada_to_vector_xada:
    name: Nexus(xADA) to Vector(xADA)
    uses: ./.github/workflows/single-transaction.yml
    needs: nexus_ap3x_to_vector_ap3x
    with:
      bridge: Skyline
      url: ${{ vars.SKYLINE_URL }}
      source_chain: Nexus
      amount: 2
      source_token: xADA
      destination_chain: Vector
      destination_token: xADA
      notification: false
    secrets:
      SIGN_KEY: ${{ secrets.SIGN_KEY }}
      CHROME_URL: ${{ secrets.CHROME_URL }}
      CHROME_CONFIGS_URL: ${{ secrets.CHROME_CONFIGS_URL }}
  nexus_mytesttoken_to_vector_mytesttoken:
    name: Nexus(myTestToken) to Vector(myTestToken)
    uses: ./.github/workflows/single-transaction.yml
    needs: nexus_xada_to_vector_xada
    with:
      bridge: Skyline
      url: ${{ vars.SKYLINE_URL }}
      source_chain: Nexus
      amount: 5
      source_token: myTestToken
      destination_chain: Vector
      destination_token: myTestToken
      notification: false
    secrets:
      SIGN_KEY: ${{ secrets.SIGN_KEY }}
      CHROME_URL: ${{ secrets.CHROME_URL }}
      CHROME_CONFIGS_URL: ${{ secrets.CHROME_CONFIGS_URL }}
  nexus_xada_to_preview_ada:
    name: Nexus(xADA) to Preview(ADA)
    uses: ./.github/workflows/single-transaction.yml
    needs: nexus_mytesttoken_to_vector_mytesttoken
    with:
      bridge: Skyline
      url: ${{ vars.SKYLINE_URL }}
      source_chain: Nexus
      amount: 2
      source_token: xADA
      destination_chain: Preview
      destination_token: ADA
      notification: false
    secrets:
      SIGN_KEY: ${{ secrets.SIGN_KEY }}
      CHROME_URL: ${{ secrets.CHROME_URL }}
      CHROME_CONFIGS_URL: ${{ secrets.CHROME_CONFIGS_URL }}
  inputs_check:
    name: Inputs Check
    runs-on: ubuntu-latest
    outputs:
      notification: ${{ steps.notification_input_check.outputs.notification }}
    steps:
      - name: Notification Input Check
        id: notification_input_check
        run: |
          if [[ "${{ inputs.notification }}" != "false" ]]; then
            echo "notification=true" >> $GITHUB_OUTPUT
          else
            echo "notification=false" >> $GITHUB_OUTPUT
          fi
  notification:
    name: Send notification
    uses: ./.github/workflows/multiple-skyline-partner-transactions-notification.yml
    needs: [prime_ap3x_to_preview_cap3x, prime_ap3x_to_vector_ap3x, prime_ap3x_to_nexus_ap3x, preview_cap3x_to_prime_ap3x, preview_ada_to_vector_xada, preview_ada_to_nexus_xada, vector_ap3x_to_prime_ap3x, vector_xada_to_preview_ada, vector_ap3x_to_nexus_ap3x, vector_xada_to_nexus_xada, vector_mytesttoken_to_nexus_mytesttoken, nexus_ap3x_to_prime_ap3x, nexus_ap3x_to_vector_ap3x, nexus_xada_to_vector_xada, nexus_mytesttoken_to_vector_mytesttoken, nexus_xada_to_preview_ada, inputs_check]
    if: (!cancelled() && (needs.inputs_check.outputs.notification == 'true'))
    with:
      bridge: Skyline
      tx_01_source_chain: Prime
      tx_01_source_token: AP3X
      tx_01_destination_chain: Preview
      tx_01_destination_token: cAP3X
      tx_01_source_status: ${{ needs.prime_ap3x_to_preview_cap3x.outputs.source_status }}
      tx_01_bridge_status: ${{ needs.prime_ap3x_to_preview_cap3x.outputs.bridge_status }}
      tx_01_destination_status: ${{ needs.prime_ap3x_to_preview_cap3x.outputs.destination_status }}
      tx_01_status: ${{ needs.prime_ap3x_to_preview_cap3x.outputs.bridging_status }}
      tx_01_logs_artifact_id: ${{ needs.prime_ap3x_to_preview_cap3x.outputs.logs_artifact_id }}
      tx_02_source_chain: Prime
      tx_02_source_token: AP3X
      tx_02_destination_chain: Vector
      tx_02_destination_token: AP3X
      tx_02_source_status: ${{ needs.prime_ap3x_to_vector_ap3x.outputs.source_status }}
      tx_02_bridge_status: ${{ needs.prime_ap3x_to_vector_ap3x.outputs.bridge_status }}
      tx_02_destination_status: ${{ needs.prime_ap3x_to_vector_ap3x.outputs.destination_status }}
      tx_02_status: ${{ needs.prime_ap3x_to_vector_ap3x.outputs.bridging_status }}
      tx_02_logs_artifact_id: ${{ needs.prime_ap3x_to_vector_ap3x.outputs.logs_artifact_id }}
      tx_03_source_chain: Prime
      tx_03_source_token: AP3X
      tx_03_destination_chain: Nexus
      tx_03_destination_token: AP3X
      tx_03_source_status: ${{ needs.prime_ap3x_to_nexus_ap3x.outputs.source_status }}
      tx_03_bridge_status: ${{ needs.prime_ap3x_to_nexus_ap3x.outputs.bridge_status }}
      tx_03_destination_status: ${{ needs.prime_ap3x_to_nexus_ap3x.outputs.destination_status }}
      tx_03_status: ${{ needs.prime_ap3x_to_nexus_ap3x.outputs.bridging_status }}
      tx_03_logs_artifact_id: ${{ needs.prime_ap3x_to_nexus_ap3x.outputs.logs_artifact_id }}
      tx_04_source_chain: Preview
      tx_04_source_token: cAP3X
      tx_04_destination_chain: Prime
      tx_04_destination_token: AP3X
      tx_04_source_status: ${{ needs.preview_cap3x_to_prime_ap3x.outputs.source_status }}
      tx_04_bridge_status: ${{ needs.preview_cap3x_to_prime_ap3x.outputs.bridge_status }}
      tx_04_destination_status: ${{ needs.preview_cap3x_to_prime_ap3x.outputs.destination_status }}
      tx_04_status: ${{ needs.preview_cap3x_to_prime_ap3x.outputs.bridging_status }}
      tx_04_logs_artifact_id: ${{ needs.preview_cap3x_to_prime_ap3x.outputs.logs_artifact_id }}
      tx_05_source_chain: Preview
      tx_05_source_token: ADA
      tx_05_destination_chain: Vector
      tx_05_destination_token: xADA
      tx_05_source_status: ${{ needs.preview_ada_to_vector_xada.outputs.source_status }}
      tx_05_bridge_status: ${{ needs.preview_ada_to_vector_xada.outputs.bridge_status }}
      tx_05_destination_status: ${{ needs.preview_ada_to_vector_xada.outputs.destination_status }}
      tx_05_status: ${{ needs.preview_ada_to_vector_xada.outputs.bridging_status }}
      tx_05_logs_artifact_id: ${{ needs.preview_ada_to_vector_xada.outputs.logs_artifact_id }}
      tx_06_source_chain: Preview
      tx_06_source_token: ADA
      tx_06_destination_chain: Nexus
      tx_06_destination_token: xADA
      tx_06_source_status: ${{ needs.preview_ada_to_nexus_xada.outputs.source_status }}
      tx_06_bridge_status: ${{ needs.preview_ada_to_nexus_xada.outputs.bridge_status }}
      tx_06_destination_status: ${{ needs.preview_ada_to_nexus_xada.outputs.destination_status }}
      tx_06_status: ${{ needs.preview_ada_to_nexus_xada.outputs.bridging_status }}
      tx_06_logs_artifact_id: ${{ needs.preview_ada_to_nexus_xada.outputs.logs_artifact_id }}
      tx_07_source_chain: Vector
      tx_07_source_token: AP3X
      tx_07_destination_chain: Prime
      tx_07_destination_token: AP3X
      tx_07_source_status: ${{ needs.vector_ap3x_to_prime_ap3x.outputs.source_status }}
      tx_07_bridge_status: ${{ needs.vector_ap3x_to_prime_ap3x.outputs.bridge_status }}
      tx_07_destination_status: ${{ needs.vector_ap3x_to_prime_ap3x.outputs.destination_status }}
      tx_07_status: ${{ needs.vector_ap3x_to_prime_ap3x.outputs.bridging_status }}
      tx_07_logs_artifact_id: ${{ needs.vector_ap3x_to_prime_ap3x.outputs.logs_artifact_id }}
      tx_08_source_chain: Vector
      tx_08_source_token: xADA
      tx_08_destination_chain: Preview
      tx_08_destination_token: ADA
      tx_08_source_status: ${{ needs.vector_xada_to_preview_ada.outputs.source_status }}
      tx_08_bridge_status: ${{ needs.vector_xada_to_preview_ada.outputs.bridge_status }}
      tx_08_destination_status: ${{ needs.vector_xada_to_preview_ada.outputs.destination_status }}
      tx_08_status: ${{ needs.vector_xada_to_preview_ada.outputs.bridging_status }}
      tx_08_logs_artifact_id: ${{ needs.vector_xada_to_preview_ada.outputs.logs_artifact_id }}
      tx_09_source_chain: Vector
      tx_09_source_token: AP3X
      tx_09_destination_chain: Nexus
      tx_09_destination_token: AP3X
      tx_09_source_status: ${{ needs.vector_ap3x_to_nexus_ap3x.outputs.source_status }}
      tx_09_bridge_status: ${{ needs.vector_ap3x_to_nexus_ap3x.outputs.bridge_status }}
      tx_09_destination_status: ${{ needs.vector_ap3x_to_nexus_ap3x.outputs.destination_status }}
      tx_09_status: ${{ needs.vector_ap3x_to_nexus_ap3x.outputs.bridging_status }}
      tx_09_logs_artifact_id: ${{ needs.vector_ap3x_to_nexus_ap3x.outputs.logs_artifact_id }}
      tx_10_source_chain: Vector
      tx_10_source_token: xADA
      tx_10_destination_chain: Nexus
      tx_10_destination_token: xADA
      tx_10_source_status: ${{ needs.vector_xada_to_nexus_xada.outputs.source_status }}
      tx_10_bridge_status: ${{ needs.vector_xada_to_nexus_xada.outputs.bridge_status }}
      tx_10_destination_status: ${{ needs.vector_xada_to_nexus_xada.outputs.destination_status }}
      tx_10_status: ${{ needs.vector_xada_to_nexus_xada.outputs.bridging_status }}
      tx_10_logs_artifact_id: ${{ needs.vector_xada_to_nexus_xada.outputs.logs_artifact_id }}
      tx_11_source_chain: Vector
      tx_11_source_token: myTestToken
      tx_11_destination_chain: Nexus
      tx_11_destination_token: myTestToken
      tx_11_source_status: ${{ needs.vector_mytesttoken_to_nexus_mytesttoken.outputs.source_status }}
      tx_11_bridge_status: ${{ needs.vector_mytesttoken_to_nexus_mytesttoken.outputs.bridge_status }}
      tx_11_destination_status: ${{ needs.vector_mytesttoken_to_nexus_mytesttoken.outputs.destination_status }}
      tx_11_status: ${{ needs.vector_mytesttoken_to_nexus_mytesttoken.outputs.bridging_status }}
      tx_11_logs_artifact_id: ${{ needs.vector_mytesttoken_to_nexus_mytesttoken.outputs.logs_artifact_id }}
      tx_12_source_chain: Nexus
      tx_12_source_token: AP3X
      tx_12_destination_chain: Prime
      tx_12_destination_token: AP3X
      tx_12_source_status: ${{ needs.nexus_ap3x_to_prime_ap3x.outputs.source_status }}
      tx_12_bridge_status: ${{ needs.nexus_ap3x_to_prime_ap3x.outputs.bridge_status }}
      tx_12_destination_status: ${{ needs.nexus_ap3x_to_prime_ap3x.outputs.destination_status }}
      tx_12_status: ${{ needs.nexus_ap3x_to_prime_ap3x.outputs.bridging_status }}
      tx_12_logs_artifact_id: ${{ needs.nexus_ap3x_to_prime_ap3x.outputs.logs_artifact_id }}
      tx_13_source_chain: Nexus
      tx_13_source_token: AP3X
      tx_13_destination_chain: Vector
      tx_13_destination_token: AP3X
      tx_13_source_status: ${{ needs.nexus_ap3x_to_vector_ap3x.outputs.source_status }}
      tx_13_bridge_status: ${{ needs.nexus_ap3x_to_vector_ap3x.outputs.bridge_status }}
      tx_13_destination_status: ${{ needs.nexus_ap3x_to_vector_ap3x.outputs.destination_status }}
      tx_13_status: ${{ needs.nexus_ap3x_to_vector_ap3x.outputs.bridging_status }}
      tx_13_logs_artifact_id: ${{ needs.nexus_ap3x_to_vector_ap3x.outputs.logs_artifact_id }}
      tx_14_source_chain: Nexus
      tx_14_source_token: xADA
      tx_14_destination_chain: Vector
      tx_14_destination_token: xADA
      tx_14_source_status: ${{ needs.nexus_xada_to_vector_xada.outputs.source_status }}
      tx_14_bridge_status: ${{ needs.nexus_xada_to_vector_xada.outputs.bridge_status }}
      tx_14_destination_status: ${{ needs.nexus_xada_to_vector_xada.outputs.destination_status }}
      tx_14_status: ${{ needs.nexus_xada_to_vector_xada.outputs.bridging_status }}
      tx_14_logs_artifact_id: ${{ needs.nexus_xada_to_vector_xada.outputs.logs_artifact_id }}
      tx_15_source_chain: Nexus
      tx_15_source_token: myTestToken
      tx_15_destination_chain: Vector
      tx_15_destination_token: myTestToken
      tx_15_source_status: ${{ needs.nexus_mytesttoken_to_vector_mytesttoken.outputs.source_status }}
      tx_15_bridge_status: ${{ needs.nexus_mytesttoken_to_vector_mytesttoken.outputs.bridge_status }}
      tx_15_destination_status: ${{ needs.nexus_mytesttoken_to_vector_mytesttoken.outputs.destination_status }}
      tx_15_status: ${{ needs.nexus_mytesttoken_to_vector_mytesttoken.outputs.bridging_status }}
      tx_15_logs_artifact_id: ${{ needs.nexus_mytesttoken_to_vector_mytesttoken.outputs.logs_artifact_id }}
      tx_16_source_chain: Nexus
      tx_16_source_token: xADA
      tx_16_destination_chain: Preview
      tx_16_destination_token: ADA
      tx_16_source_status: ${{ needs.nexus_xada_to_preview_ada.outputs.source_status }}
      tx_16_bridge_status: ${{ needs.nexus_xada_to_preview_ada.outputs.bridge_status }}
      tx_16_destination_status: ${{ needs.nexus_xada_to_preview_ada.outputs.destination_status }}
      tx_16_status: ${{ needs.nexus_xada_to_preview_ada.outputs.bridging_status }}
      tx_16_logs_artifact_id: ${{ needs.nexus_xada_to_preview_ada.outputs.logs_artifact_id }}
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
