---
name: Reactor Test
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  security-events: write

jobs:
  prime_to_vector:
    name: Prime to Vector
    uses: ./.github/workflows/bridging.yml
    with:
      source: prime
      destination: vector
      amount: 5
    secrets:
      SIGN_KEY: ${{ secrets.SIGN_KEY }}
      PRIME_WALLET_RECOVERY_PHRASE: ${{ secrets.PRIME_WALLET_RECOVERY_PHRASE }}
      VECTOR_WALLET_RECOVERY_PHRASE: ${{ secrets.VECTOR_WALLET_RECOVERY_PHRASE }}
  prime_to_nexus:
    name: Prime to Nexus
    uses: ./.github/workflows/bridging.yml
    with:
      source: prime
      destination: nexus
      amount: 5
    secrets:
      SIGN_KEY: ${{ secrets.SIGN_KEY }}
      PRIME_WALLET_RECOVERY_PHRASE: ${{ secrets.PRIME_WALLET_RECOVERY_PHRASE }}
      NEXUS_WALLET_RECOVERY_PHRASE: ${{ secrets.NEXUS_WALLET_RECOVERY_PHRASE }}
  vector_to_prime:
    name: Vector to Prime
    uses: ./.github/workflows/bridging.yml
    with:
      source: vector
      destination: prime
      amount: 2
    secrets:
      SIGN_KEY: ${{ secrets.SIGN_KEY }}
      VECTOR_WALLET_RECOVERY_PHRASE: ${{ secrets.VECTOR_WALLET_RECOVERY_PHRASE }}
      PRIME_WALLET_RECOVERY_PHRASE: ${{ secrets.PRIME_WALLET_RECOVERY_PHRASE }}
  nexus_to_prime:
    name: Nexus to Prime
    uses: ./.github/workflows/bridging.yml
    with:
      source: nexus
      destination: prime
      amount: 2
    secrets:
      SIGN_KEY: ${{ secrets.SIGN_KEY }}
      NEXUS_WALLET_RECOVERY_PHRASE: ${{ secrets.NEXUS_WALLET_RECOVERY_PHRASE }}
      PRIME_WALLET_RECOVERY_PHRASE: ${{ secrets.PRIME_WALLET_RECOVERY_PHRASE }}
  notification:
    name: Send notification
    uses: ./.github/workflows/notification-reactor-test.yml
    needs: [prime_to_vector, prime_to_nexus, vector_to_prime, nexus_to_prime]
    with:
      tx_01_source_status: ${{ needs.prime_to_vector.outputs.source_status }}
      tx_01_bridge_status: ${{ needs.prime_to_vector.outputs.bridge_status }}
      tx_01_destination_status: ${{ needs.prime_to_vector.outputs.destination_status }}
      tx_01_status: ${{ needs.prime_to_vector.outputs.bridging_status }}
      tx_02_source_status: ${{ needs.prime_to_nexus.outputs.source_status }}
      tx_02_bridge_status: ${{ needs.prime_to_nexus.outputs.bridge_status }}
      tx_02_destination_status: ${{ needs.prime_to_nexus.outputs.destination_status }}
      tx_02_status: ${{ needs.prime_to_nexus.outputs.bridging_status }}
      tx_03_source_status: ${{ needs.vector_to_prime.outputs.source_status }}
      tx_03_bridge_status: ${{ needs.vector_to_prime.outputs.bridge_status }}
      tx_03_destination_status: ${{ needs.vector_to_prime.outputs.destination_status }}
      tx_03_status: ${{ needs.vector_to_prime.outputs.bridging_status }}
      tx_04_source_status: ${{ needs.nexus_to_prime.outputs.source_status }}
      tx_04_bridge_status: ${{ needs.nexus_to_prime.outputs.bridge_status }}
      tx_04_destination_status: ${{ needs.nexus_to_prime.outputs.destination_status }}
      tx_04_status: ${{ needs.nexus_to_prime.outputs.bridging_status }}
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
