---
name: Single Transaction
on:
  workflow_dispatch:
    inputs:
      bridge:
        required: true
        description: Bridge
        type: choice
        options:
          - Reactor
          - Skyline

      url:
        required: true
        description: URL
        type: choice
        options:
          - https://reactor.testnet.apexfusion.org/
          - https://skyline.testnet.ethernal.work/

      source_chain:
        required: true
        description: Source chain
        type: choice
        options:
          - Prime
          - Vector
          - Nexus
          - Preview

      source_token:
        required: true
        description: Source token
        type: choice
        options:
          - AP3X
          - ADA
          - cAP3X
          - xADA
          - myTestToken

      destination_chain:
        required: true
        description: Destination chain
        type: choice
        options:
          - Prime
          - Vector
          - Nexus
          - Preview

      destination_token:
        required: true
        description: Destination token
        type: choice
        options:
          - AP3X
          - ADA
          - cAP3X
          - xADA
          - myTestToken

      amount:
        required: true
        description: Amount to send from Source to Destination
        type: string

      notification:
        required: false
        description: Notification
        type: boolean
        default: true

  workflow_call:
    inputs:
      bridge:
        required: true
        description: Bridge
        type: string

      url:
        required: true
        description: URL
        type: string

      source_chain:
        required: true
        description: Source chain
        type: string

      source_token:
        required: true
        description: Source token
        type: string

      destination_chain:
        required: true
        description: Destination chain
        type: string

      destination_token:
        required: true
        description: Destination token
        type: string

      amount:
        required: true
        description: Amount to send from Source to Destination
        type: string

      notification:
        required: true
        description: Notification
        type: boolean

    outputs:
      bridging_status:
        value: ${{ jobs.bridging.outputs.bridging_status }}

    secrets:
      SIGN_KEY:
        required: true

      CHROME_URL:
        required: true

      CHROME_CONFIGS_URL:
        required: true

permissions:
  id-token: write
  contents: read
  security-events: write

jobs:
  bridging:
    name: "${{ inputs.source_chain }} ${{ inputs.source_token }} to ${{ inputs.destination_chain }} ${{ inputs.destination_token }}"
    runs-on: macos-latest
    outputs:
      bridging_status: ${{ steps.bridging_status.outputs.result }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2

      - name: Setup Python 3.9
        uses: actions/setup-python@v6.2.0
        with:
          python-version: "3.9"
          check-latest: true
          cache: "pip"

      - name: Change Google Chrome For Testing version
        run: |
          sudo rm -rf /Applications/Google\ Chrome\ for\ Testing.app
          wget -q -O chrome.zip "${{ secrets.CHROME_URL }}"
          unzip -q chrome.zip
          sudo mv chrome-mac-arm64/Google\ Chrome\ for\ Testing.app /Applications

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Start bridging
        run: python main.py ${{ inputs.bridge }} ${{ inputs.source_chain }} ${{ inputs.amount }} ${{ inputs.source_token }} ${{ inputs.destination_chain }}
        env:
          PYTHONUNBUFFERED: 1
          SIGN_KEY: ${{ secrets.SIGN_KEY }}
          BRIDGE_URL: ${{ inputs.url }}
          APEX_FUSION_FAUCET_URL: ${{ vars.APEX_FUSION_FAUCET_URL }}
          CHROMEDRIVER_VERSION: ${{ vars.CHROMEDRIVER_VERSION }}
          CHROME_CONFIGS_URL: ${{ secrets.CHROME_CONFIGS_URL }}

      - name: Archive status
        if: (!cancelled())
        uses: actions/upload-artifact@v7.0.1
        with:
          name: ${{ inputs.source_chain }}_${{ inputs.source_token }}_to_${{ inputs.destination_chain }}_${{ inputs.destination_token }}_statuses
          path: statuses.json
          retention-days: 7

      - name: Archive logs
        if: (!cancelled())
        id: logs-artifact-upload
        uses: actions/upload-artifact@v7.0.1
        with:
          name: ${{ inputs.source_chain }}_${{ inputs.source_token }}_to_${{ inputs.destination_chain }}_${{ inputs.destination_token }}_logs
          path: logs/*
          retention-days: 7

      - name: Generate statuses of the bridging process
        if: (!cancelled())
        id: bridging_status
        run: |
          json=$(jq -c \
            --arg logs_artifact_id "${{ steps.logs-artifact-upload.outputs.artifact-id }}" \
            '. + {logs_artifact_id: $logs_artifact_id}' \
            statuses.json)
          echo "result=$json" >> $GITHUB_OUTPUT

  notification:
    name: Send notification
    uses: ./.github/workflows/single-notification.yml
    needs: bridging
    if: ((success() || failure()) && inputs.notification)
    with:
      bridge: ${{ inputs.bridge }}
      source_chain: ${{ inputs.source_chain }}
      source_token: ${{ inputs.source_token }}
      destination_chain: ${{ inputs.destination_chain }}
      destination_token: ${{ inputs.destination_token }}
      bridging_status: ${{ needs.bridging.outputs.bridging_status }}
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
