---
name: Source Nexus Transactions

on:
  workflow_call:
    inputs:
      bridge_name:
        type: string
        required: true
      notification:
        type: boolean
        required: true

    outputs:
      transactions:
        value: ${{ jobs.notification.outputs.transactions }}

permissions:
  id-token: write
  contents: read
  security-events: write

jobs:
  nexus_ap3x_to_prime_ap3x:
    name: Nexus(AP3X) to Prime(AP3X)
    uses: ./.github/workflows/single-transaction.yml
    with:
      bridge_name: ${{ inputs.bridge_name }}
      source_chain: Nexus
      amount: 2
      source_token: AP3X
      destination_chain: Prime
      destination_token: AP3X
      notification: false
    secrets: inherit
  
  nexus_ap3x_to_vector_ap3x:
    name: Nexus(AP3X) to Vector(AP3X)
    uses: ./.github/workflows/single-transaction.yml
    needs: nexus_ap3x_to_prime_ap3x
    with:
      bridge_name: ${{ inputs.bridge_name }}
      source_chain: Nexus
      amount: 2
      source_token: AP3X
      destination_chain: Vector
      destination_token: AP3X
      notification: false
    secrets: inherit

  nexus_xada_to_preview_ada:
    name: Nexus(xADA) to Preview(ADA)
    uses: ./.github/workflows/single-transaction.yml
    if: ${{ inputs.bridge_name == 'Skyline' }}
    needs: nexus_ap3x_to_vector_ap3x
    with:
      bridge_name: ${{ inputs.bridge_name }}
      source_chain: Nexus
      amount: 2
      source_token: xADA
      destination_chain: Preview
      destination_token: ADA
      notification: false
    secrets: inherit

  nexus_mytesttoken_to_preview_mytesttoken:
    name: Nexus(myTestToken) to Preview(myTestToken)
    uses: ./.github/workflows/single-transaction.yml
    if: ${{ inputs.bridge_name == 'Skyline' }}
    needs: nexus_xada_to_preview_ada
    with:
      bridge_name: ${{ inputs.bridge_name }}
      source_chain: Nexus
      amount: 2
      source_token: myTestToken
      destination_chain: Preview
      destination_token: myTestToken
      notification: false
    secrets: inherit

  nexus_xada_to_vector_xada:
    name: Nexus(xADA) to Vector(xADA)
    uses: ./.github/workflows/single-transaction.yml
    if: ${{ inputs.bridge_name == 'Skyline' }}
    needs: nexus_mytesttoken_to_preview_mytesttoken
    with:
      bridge_name: ${{ inputs.bridge_name }}
      source_chain: Nexus
      amount: 2
      source_token: xADA
      destination_chain: Vector
      destination_token: xADA
      notification: false
    secrets: inherit

  nexus_mytesttoken_to_vector_mytesttoken:
    name: Nexus(myTestToken) to Vector(myTestToken)
    uses: ./.github/workflows/single-transaction.yml
    if: ${{ inputs.bridge_name == 'Skyline' }}
    needs: nexus_xada_to_vector_xada
    with:
      bridge_name: ${{ inputs.bridge_name }}
      source_chain: Nexus
      amount: 5
      source_token: myTestToken
      destination_chain: Vector
      destination_token: myTestToken
      notification: false
    secrets: inherit

  nexus_ap3x_to_polygon_xpol:
    name: Nexus(AP3X) to Vector(xPOL)
    uses: ./.github/workflows/single-transaction.yml
    if: ${{ inputs.bridge_name == 'Skyline' }}
    needs: nexus_mytesttoken_to_vector_mytesttoken
    with:
      bridge_name: ${{ inputs.bridge_name }}
      source_chain: Nexus
      amount: 5
      source_token: AP3X
      destination_chain: Vector
      destination_token: xPOL
      notification: false
    secrets: inherit

  nexus_xpol_to_polygon_xpol:
    name: Nexus(xPOL) to Vector(xPOL)
    uses: ./.github/workflows/single-transaction.yml
    if: ${{ inputs.bridge_name == 'Skyline' }}
    needs: nexus_ap3x_to_polygon_xpol
    with:
      bridge_name: ${{ inputs.bridge_name }}
      source_chain: Nexus
      amount: 5
      source_token: xPOL
      destination_chain: Vector
      destination_token: xPOL
      notification: false
    secrets: inherit

  notification:
    name: Notification
    uses: ./.github/workflows/notification.yml
    if: (!cancelled() && inputs.notification)
    needs:
      - nexus_ap3x_to_prime_ap3x
      - nexus_ap3x_to_vector_ap3x
      - nexus_xada_to_preview_ada
      - nexus_mytesttoken_to_preview_mytesttoken
      - nexus_xada_to_vector_xada
      - nexus_mytesttoken_to_vector_mytesttoken
      - nexus_ap3x_to_polygon_xpol
      - nexus_xpol_to_polygon_xpol
    with:
      needs_json: ${{ toJSON(needs) }}
      bridge_name: ${{ inputs.bridge_name }}
    secrets: inherit
