---
name: Source Sei Transactions

on:
  workflow_call:
    inputs:
      bridge_name:
        type: string
        required: true
      notification:
        type: boolean
        required: true

    outputs:
      transactions:
        value: ${{ jobs.notification.outputs.transactions }}

permissions:
  id-token: write
  contents: read
  security-events: write

jobs:
  sei_sei_to_preview_sei:
    name: Sei(SEI) to Preview(SEI)
    uses: ./.github/workflows/single-transaction.yml
    if: ${{ inputs.bridge_name == 'Skyline' }}
    with:
      bridge_name: ${{ inputs.bridge_name }}
      source_chain: Sei
      amount: 6
      source_token: SEI
      destination_chain: Preview
      destination_token: SEI
      notification: false
    secrets: inherit

  notification:
    name: Notification
    uses: ./.github/workflows/notification.yml
    if: (!cancelled() && inputs.notification)
    needs:
      - sei_sei_to_preview_sei
    with:
      needs_json: ${{ toJSON(needs) }}
      bridge_name: ${{ inputs.bridge_name }}
    secrets: inherit
