---
name: Source Unichain Transactions

on:
  workflow_call:
    inputs:
      bridge_name:
        type: string
        required: true
      notification:
        type: boolean
        required: true

    outputs:
      transactions:
        value: ${{ jobs.notification.outputs.transactions }}

permissions:
  id-token: write
  contents: read
  security-events: write

jobs:
  unichain_eth_to_preview_cunichaineth:
    name: Unichain(ETH) to Preview(cUnichainETH)
    uses: ./.github/workflows/single-transaction.yml
    if: ${{ inputs.bridge_name == 'Skyline' }}
    with:
      bridge_name: ${{ inputs.bridge_name }}
      source_chain: Unichain
      amount: 0.0005
      source_token: ETH
      destination_chain: Preview
      destination_token: cUnichainETH
      notification: false
    secrets: inherit

  notification:
    name: Notification
    uses: ./.github/workflows/notification.yml
    if: (!cancelled() && inputs.notification)
    needs:
      - unichain_eth_to_preview_cunichaineth
    with:
      needs_json: ${{ toJSON(needs) }}
      bridge_name: ${{ inputs.bridge_name }}
    secrets: inherit
