---
name: Source Scroll Transactions

on:
  workflow_call:
    inputs:
      bridge_name:
        type: string
        required: true

    outputs:
      transactions:
        value: ${{ jobs.collect.outputs.transactions }}

permissions:
  id-token: write
  contents: read
  security-events: write

jobs:
  scroll_eth_to_preview_cscrolleth:
    name: Scroll(ETH) to Preview(cScrollETH)
    uses: ./.github/workflows/single-transaction.yml
    if: ${{ inputs.bridge_name == 'Skyline' }}
    with:
      bridge_name: ${{ inputs.bridge_name }}
      source_chain: Scroll
      amount: 0.0005
      source_token: ETH
      destination_chain: Preview
      destination_token: cScrollETH
      notification: false
    secrets: inherit

  collect:
    name: Collect
    uses: ./.github/workflows/collect-transactions.yml
    if: (!cancelled())
    needs:
      - scroll_eth_to_preview_cscrolleth
    with:
      needs_json: ${{ toJSON(needs) }}
      source_chain: Scroll
